version: '3.8'

services:
  postgres:
    image: "postgres"
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - back/.env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    restart: unless-stopped
    image: "<dockername>/backend"
    ports:
      - "8000:8000"
    env_file:
      - back/.env
    depends_on:
      - postgres
    volumes:
      - ./back:/app
      - images_volume:/app/images
    networks:
      - app-network

  frontend:
    image: "<dockername>/frontend"
    ports:
      - "3000:3000"
    env_file:
      - front/.env
    depends_on:
      - backend
    tty: true
    networks:
      - app-network

  # nginx:
  #   build: ./nginx
  #   # env_file: .env
  #   restart: always
  #   depends_on:
  #     - backend 

networks:
  app-network:
    driver: bridge

volumes:
  postgres:
  images_volume:
