version: '3.8'

services:
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    # environment:
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=password123
    #   - POSTGRES_DB=rust_admin
    env_file:
      - back/.env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres:
